[package]
name = "player-pc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "player"
path = "src/main.rs"

[dependencies]
player-core.workspace = true
player-audio.workspace = true

directories.workspace = true
eframe.workspace = true
image.workspace = true
rfd.workspace = true

[lints]
workspace = true
