org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# ABIs que o cargo-ndk compila. x86_64 fica pro emulador; drope-o num release
# menor. Sobrescrevível: -PyasmineAbis=arm64-v8a
yasmineAbis=arm64-v8a,armeabi-v7a,x86_64
