[package]
name = "player-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
jwalk.workspace = true
lofty.workspace = true
rayon.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
blake3.workspace = true
uuid.workspace = true
unicode-normalization = "0.1"

[lints]
workspace = true
